# REFERENCE: 
# https://segmentfault.com/a/1190000009054888
# http://www.yanglangjing.com/2018/08/28/travis_ci_auto_deploy_hexo_to_vps/
# https://notes.iissnan.com/2016/publishing-github-pages-with-travis-ci/
language: node_js
node_js: stable
branches:
  only:
    - source_files
    - hexo_template
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - export TZ="Asia/Shanghai"
  - git config user.name "MiaoDX"
  - git config user.email "miaodx@hotmail.com"
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo clean
  # - npm install gulp
  # - hexo g && gulp # we generate after resources are retrieved
after_script:
  - git clone --depth 1 https://${GH_REF} -b hexo_template .deploy_git
  - cd .deploy_git

  - pwd
  - ls -a

  # Get resource files
  - git clone --depth 1 https://${GH_REF} -b source_files ./source/_posts/source_files
  # Theme
  - git clone --depth 1 https://github.com/iissnan/hexo-theme-next.git -b v5.1.4 ./themes/next
  
  - pwd
  - ls -a

  - hexo g

  # - rm .git/ -rf
  - cd ./public
  - pwd
  - ls -a
  
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${HEXO_TOKEN}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/MiaoDX/MiaoDX.github.io.git
notifications:
  email:
    - miaodx@hotmail.com
  on_success: change
  on_failure: always