language: 
   - python

python:
   - "3.6"

before_script:
   # - gem install travis

script:
   -

after_script:
  # https://blog.travis-ci.com/2013-01-28-token-token-token
  # - curl -LO --retry 3 https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
  # - chmod +x trigger.sh
  # - ./trigger.sh MiaoDX MiaoDX.github.io hexo_template $HEXO_TOKEN # the token is GitHub Token, will install travis (take extra time), but with only one token
  - curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
  # - sh trigger-travis.sh --branch hexo_template miaodx https://github.com/MiaoDX/MiaoDX.github.io.git $TRAVIS_ACCESS_TOKEN # THIS IS WRONG, see below
  - sh trigger-travis.sh --branch hexo_template MiaoDX MiaoDX.github.io $TRAVIS_ACCESS_TOKEN # make sure MiaoDX, not miaodx, and repo is just name, the token is Access Token