# REFERENCE: 
# https://segmentfault.com/a/1190000009054888
# http://www.yanglangjing.com/2018/08/28/travis_ci_auto_deploy_hexo_to_vps/
# https://notes.iissnan.com/2016/publishing-github-pages-with-travis-ci/

# https://blog.travis-ci.com/2018-11-08-xenial-release, 
# As shown in https://packages.ubuntu.com/search?keywords=pandoc, xenial still won't support pandoc>2.x
# so, we use lower version of pandoc, https://github.com/wzpan/hexo-renderer-pandoc/pull/22#issuecomment-426513496
# dist: xenial
language: node_js
node_js: stable

git: # https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
  depth: 1

branches:
  only:
    # - source_files
    - hexo_template
cache:
  apt: false
  # apt: true
  # directories:
    # - node_modules

before_install:
  - export TZ="Asia/Shanghai"
  - git config user.name "MiaoDX"
  - git config user.email "miaodx@hotmail.com"
  - npm install -g hexo-cli

install:
  - npm install

before_script:
  # https://github.com/wzpan/hexo-renderer-pandoc/pull/22
  - sudo apt-get -qq update
  # - sudo apt-get install -y pandoc # the pandoc plugin needs pandoc version 2.x
  - wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
  - sudo dpkg -i pandoc-2.5-1-amd64.deb
  - pip install --user pandoc-fignos pandoc-eqnos # for pandoc filter, https://github.com/travis-ci/travis-ci/issues/8378#issuecomment-328484987

script:
  # WE are already in hexo_template directory
  # - git clone https://${GH_REF} -b hexo_template .deploy_git
  # - cd .deploy_git
  - pwd
  - ls -a

  # Get resource files
  - git clone https://${GH_REF} -b source_files ./source/_posts/blogs
  # Theme
  - git clone https://github.com/iissnan/hexo-theme-next.git -b v5.1.4 ./themes/next
  - mv ./themes/_config_next.yml ./themes/next/_config.yml
  # Handle picture/resources directory
  - sh move_ims.sh

  - hexo clean
  - hexo g

after_script:  
  - cd ./public
  - pwd
  - ls -a

  - git init # fresh git in not versioned directory
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${HEXO_TOKEN}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/MiaoDX/MiaoDX.github.io.git

notifications:
  email:
    - miaodx@hotmail.com
  on_success: never # not notify
  on_failure: always