language: 
   - python

python:
   - "3.6"

before_script:
   - gem install travis

script:
   -

after_script:
   - curl -LO --retry 3 https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
   - chmod +x trigger.sh
   # - ./trigger.sh stephanmg downstream master $TRAVIS_ACCESS_TOKEN 
   - ./trigger.sh MiaoDX MiaoDX.github.io hexo_template $HEXO_TOKEN
  # - curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
  # - sh trigger-travis.sh --branch hexo_template miaodx https://github.com/MiaoDX/MiaoDX.github.io.git $HEXO_TOKEN
  # - sh trigger-travis.sh --branch hexo_template MiaoDX MiaoDX.github.io $HEXO_TOKEN # make sure MiaoDX, not miaodx, and repo is just name